import 'package:flutter/material.dart';
import 'courier_job_pool_page.dart';
import 'data/app_data_service.dart';

class CourierProfilePage extends StatefulWidget { const CourierProfilePage({super.key}); @override State<CourierProfilePage> createState()=>_S(); }
class _S extends State<CourierProfilePage>{
 static const blue=Color(0xFF168CF5),navy=Color(0xFF10213E),muted=Color(0xFF718198),bg=Color(0xFFF5FAFF);
 bool online=true,notifications=true,loading=true; String name='Kurye',phone='',email='',vehicle='Motosiklet',plate='',iban='',language='Türkçe';
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final p=await AppDataService.instance.getProfile();if(mounted)setState((){name=(p['full_name']??'Kurye').toString();phone=(p['phone']??'').toString();email=(p['email']??'').toString();notifications=p['notifications_enabled']!=false;language=(p['language']??'Türkçe').toString();loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
 Future<String?> ask(String t,String v)async{final c=TextEditingController(text:v);final r=await showDialog<String>(context:context,builder:(x)=>AlertDialog(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22)),title:Text(t),content:TextField(controller:c,autofocus:true,decoration:const InputDecoration(border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,c.text.trim()),child:const Text('Kaydet'))]));c.dispose();return r;}
 void msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 Future<void> personal()async{final n=await ask('Ad Soyad',name);if(n==null)return;final p=await ask('Telefon',phone);if(p==null)return;final e=await ask('E-posta',email);if(e==null)return;try{await AppDataService.instance.updateProfile(fullName:n,phone:p,email:e);setState((){name=n;phone=p;email=e;});msg('Bilgiler kaydedildi.');}catch(e){msg('Kaydedilemedi: $e');}}
 Future<void> vehicleEdit()async{final v=await ask('Araç',vehicle);if(v==null)return;final p=await ask('Plaka',plate);if(p==null)return;setState((){vehicle=v;plate=p;});msg('Araç bilgileri kaydedildi.');}
 Future<void> payment()async{final v=await ask('IBAN',iban);if(v!=null){setState(()=>iban=v);msg('Ödeme bilgisi kaydedildi.');}}
 void docs()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Ehliyet & Belgeler',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),for(final s in ['Ehliyet','Ruhsat','Sigorta'])ListTile(leading:const Icon(Icons.description),title:Text(s),subtitle:const Text('Kontrol bekliyor'),trailing:TextButton(onPressed:()=>msg('$s yükleme seçildi.'),child:const Text('Yükle')))])));
 void settings()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>StatefulBuilder(builder:(x,ss)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Uygulama Ayarları',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),SwitchListTile(title:const Text('Bildirimler'),value:notifications,onChanged:(v)async{ss(()=>notifications=v);setState(()=>notifications=v);try{await AppDataService.instance.updateProfile(notificationsEnabled:v);}catch(_){}}),ListTile(title:const Text('Dil'),subtitle:Text(language),trailing:const Icon(Icons.chevron_right),onTap:()async{final v=await ask('Dil',language);if(v!=null){setState(()=>language=v);try{await AppDataService.instance.updateProfile(language:v);}catch(_){}}}),const ListTile(leading:Icon(Icons.navigation),title:Text('Konum & Navigasyon'),subtitle:Text('Aktif'))]))));
 void support()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(x)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Yardım & Destek',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),ListTile(leading:const Icon(Icons.chat),title:const Text('Destek talebi oluştur'),onTap:()=>msg('Destek talebi oluşturuldu.')),const ListTile(leading:Icon(Icons.help_outline),title:Text('Sık Sorulan Sorular'))])));
 @override Widget build(BuildContext c)=>Scaffold(backgroundColor:bg,body:SafeArea(child:Column(children:[Expanded(child:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(18),children:[header(),const SizedBox(height:20),profile(),const SizedBox(height:16),stats(),const SizedBox(height:16),vehicleCard(),const SizedBox(height:16),status(),const SizedBox(height:16),menus(),const SizedBox(height:16),logout()]),nav()])));
 Widget header()=>Row(children:[icon(Icons.arrow_back,()=>Navigator.maybePop(context)),const Expanded(child:Column(children:[Text('Kurye Profilim',style:TextStyle(color:navy,fontSize:25,fontWeight:FontWeight.w900)),Text('Hesabını yönet, bilgilerini güncelle.',style:TextStyle(color:muted))])),icon(Icons.settings,settings)]); Widget icon(IconData i,VoidCallback f)=>IconButton.filledTonal(onPressed:f,icon:Icon(i));
 Widget profile()=>Row(children:[InkWell(onTap:()=>msg('Profil fotoğrafı değiştirme açıldı.'),child:const CircleAvatar(radius:52,backgroundColor:Color(0xFFE4F2FF),child:Icon(Icons.person,color:blue,size:62))),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name.isEmpty?'Kurye':name,style:const TextStyle(color:navy,fontSize:22,fontWeight:FontWeight.w900)),Text(phone.isEmpty?'Telefon ekle':phone,style:const TextStyle(color:muted)),const SizedBox(height:7),const Text('⭐ 4.9  •  320 değerlendirme',style:TextStyle(color:navy,fontWeight:FontWeight.bold))]))]);
 Widget stats()=>Row(children:[stat('1.248','Teslimat'),const SizedBox(width:8),stat('%98','Başarı'),const SizedBox(width:8),stat('4.9','Puan')]);Widget stat(String a,String b)=>Expanded(child:Container(height:82,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(a,style:const TextStyle(color:navy,fontSize:19,fontWeight:FontWeight.bold)),Text(b,style:const TextStyle(color:muted))])));
 Widget vehicleCard()=>InkWell(onTap:vehicleEdit,child:card(Row(children:[const CircleAvatar(radius:30,child:Icon(Icons.two_wheeler,size:35)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(vehicle,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text(plate.isEmpty?'Plaka ekle':plate)])),const Icon(Icons.edit,color:blue)])));
 Widget status()=>card(Row(children:[const Icon(Icons.power_settings_new,color:blue,size:30),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Çalışma Durumu',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text(online?'Yeni iş alabilirsin.':'Çevrimdışısın.')])),Switch(value:online,onChanged:(v)=>setState(()=>online=v))]));
 Widget card(Widget w)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24)),child:w);
 Widget menus(){final a=[(Icons.person,'Kişisel Bilgiler',personal),(Icons.description,'Ehliyet & Belgeler',docs),(Icons.account_balance,'Ödeme Bilgileri',payment),(Icons.settings,'Uygulama Ayarları',settings),(Icons.support_agent,'Yardım & Destek',support)];return card(Column(children:[for(final x in a)ListTile(onTap:x.$3,leading:CircleAvatar(child:Icon(x.$1)),title:Text(x.$2,style:const TextStyle(fontWeight:FontWeight.bold)),trailing:const Icon(Icons.chevron_right))]));}
 Widget logout()=>FilledButton.icon(onPressed:()async{final y=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:const Text('Çıkış yapılsın mı?'),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Çıkış Yap'))]));if(y==true){await AppDataService.instance.client.auth.signOut();msg('Çıkış yapıldı.');}},icon:const Icon(Icons.logout),label:const Text('Çıkış Yap'),style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(55),backgroundColor:const Color(0xFFFFEDEE),foregroundColor:Colors.red));
 Widget nav()=>card(Row(children:[navI(Icons.home,'Anasayfa',()=>Navigator.maybePop(context)),navI(Icons.inventory_2,'İşler',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const CourierJobPoolPage()))),navI(Icons.bar_chart,'Kazançlar',()=>msg('Kazançlar açıldı.')),navI(Icons.person,'Profil',(){},on:true)]));Widget navI(IconData i,String s,VoidCallback f,{bool on=false})=>Expanded(child:InkWell(onTap:f,child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(i,color:on?blue:muted),Text(s,style:TextStyle(fontSize:10,color:on?blue:muted))])));
}
